app/models/game.rb

round enum in game model from array to hash

---

app/controllers/game_teams_controller.rb
app/controllers/game_users_controller.rb
app/controllers/game_words_controller.rb
app/controllers/games_controller.rb
app/controllers/words_controller.rb
test/controllers/game_teams_controller_test.rb
test/controllers/game_users_controller_test.rb
test/controllers/game_words_controller_test.rb
test/controllers/games_controller_test.rb
test/controllers/words_controller_test.rb

generation of all controllers and views folders

---

app/views/games/index.html.erb
config/routes.rb

creation of resources in routes.rb and views in views folders

---

app/controllers/game_users_controller.rb
app/controllers/games_controller.rb
app/models/game.rb
app/models/game_team.rb
app/models/game_user.rb
app/views/game_users/new.html.erb
app/views/game_words/new.html.erb
config/routes.rb
db/migrate/20200319122941_remove_field_game_team_id_from_table_game_users.rb
db/schema.rb

Game user creation for main player

---

app/assets/stylesheets/components/_index.scss
app/javascript/packs/join.js
app/views/game_users/new.html.erb
app/views/games/index.html.erb
app/views/layouts/application.html.erb

added pack/join.js
fake test form landing page
hide-form class in _index.css
Pls merge! @InesMaatalla

show join form index page

---

app/models/game_team.rb
app/models/game_user.rb
db/migrate/20200319164002_add_game_team_id_to_game_users.rb
db/schema.rb

re-added game_team_id to game_users

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb

Reajustment to footer, navbar avatar & @mediaquerie to body to fit browser size.
Pls merge! @Mo-Din

fit in Browsers

---

app/controllers/game_users_controller.rb
app/views/game_users/index.html.erb

Only the game initiator (master user) see the start button on game_user index
Pls merge

only game_user user_id 1 see start button on game_users index

---

app/models/game_word.rb
db/migrate/20200321152355_remove_field_word_id_from_table_game_user.rb
db/migrate/20200321152720_add_name_to_game_words.rb
db/schema.rb

update colum word_id to name in game_words

---

app/controllers/games_controller.rb

teams creation on create game button

---

app/controllers/game_users_controller.rb
app/views/game_users/index.html.erb

player by team

---

app/controllers/game_users_controller.rb
app/controllers/games_controller.rb
app/views/game_users/index.html.erb

Main player ias associated to team one when new game is created
Please Merge @InesMaatalla

main player to team one

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_round_show.scss
app/controllers/games_controller.rb
app/javascript/packs/start_round.js
app/models/game.rb
app/models/game_word.rb
app/views/game_users/index.html.erb
app/views/games/show.html.erb
app/views/layouts/application.html.erb
db/migrate/20200325000235_remove_stautus_from_words.rb
db/migrate/20200325000439_add_stautus_to_game_words.rb
db/migrate/20200325000632_add_order_to_game_users.rb
db/migrate/20200325000814_add_current_user_to_games.rb
db/schema.rb

field added to game-words, game-users, games. Creation of start_round… js and round_show.scss components

Migration to start game flow

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_timer.scss
app/controllers/games_controller.rb
app/javascript/packs/clock.js
app/javascript/packs/start_round.js
app/views/games/show.html.erb
app/views/layouts/application.html.erb
db/migrate/20200325124556_change_order_to_be_bigint_in_game_users.rb
db/schema.rb

Show first word, user name and timer (_timer.scss/clock.js)
Pls merge

Show current user items on games/show

---

app/models/game_word.rb

words have enum:in status on creation

---

app/views/games/show.html.erb

if conditions allowing current_user as player to see word and point button
Pls merge

Player or not game show options visibility

---

app/controllers/game_teams_controller.rb
app/controllers/games_controller.rb
app/views/games/show.html.erb
config/routes.rb

score updating

---

app/views/game_users/index.html.erb

rady button if path modified

---

app/views/game_users/index.html.erb

js tag moved to bottom

---

app/controllers/game_words_controller.rb
app/models/game_word.rb
app/views/game_users/index.html.erb

ready for all in game team page & words validations

---

app/controllers/games_controller.rb
app/javascript/packs/game_updates.js
app/models/game.rb
app/models/user.rb
app/views/games/show.html.erb

Arrays to manage players and words

---

db/migrate/20200330164847_remove_game_user_id_from_games.rb
db/schema.rb

removed game_user_id from games table

column removed

---

app/controllers/game_teams_controller.rb
app/controllers/game_users_controller.rb
app/controllers/games_controller.rb
app/javascript/packs/clock.js
app/javascript/packs/game_updates.js
app/models/game.rb
app/models/game_team.rb
app/models/game_user.rb
app/models/user.rb
app/views/games/show.html.erb
db/migrate/20200330164847_remove_game_user_id_from_games.rb
db/migrate/20200331234948_add_active_to_game_teams.rb
db/migrate/20200401000230_add_active_to_game_users.rb
db/migrate/20200401000359_add_seconds_left_to_games.rb
db/schema.rb

global models-controllers refactored

---

app/javascript/packs/join.js
app/views/games/show.html.erb
db/seeds.rb
lib/tasks/game_timers.rake

game_timers task was missing, added a seed and modification of pack/join.js

Added a rake task for timer

---

lib/tasks/game_timers.rake

sleep in game_timers task pass fron 1 to 0.1

---

app/views/game_users/index.html.erb
app/views/games/show.html.erb

Moved start from game show to game_users/index
pls merge

Remove start from show

---

app/views/game_users/index.html.erb

ready if not master user on game_users/index

---

app/assets/stylesheets/components/card.scss
app/views/games/show.html.erb

remove card-player from non player view + minimize card player margin

---

app/assets/stylesheets/components/_index.scss

+ container margin to auto and max-width to 700px;
pls merge @Mo-Din

html to position relative & height 100

---

config/environments/production.rb

local to cloudinary in prod.rb

---

app/assets/stylesheets/components/_end-page.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_player-screen.scss
app/javascript/packs/noizes.js
app/views/games/show.html.erb
app/views/shared/_end-page.html.erb

buzzer audio, round & card-player position, text position end page
